from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path


def find_project_root() -> Path:
    for candidate in Path(__file__).resolve().parents:
        if (candidate / "pyproject.toml").is_file():
            return candidate
    raise RuntimeError("could not locate project root")


PROJECT_ROOT = find_project_root()
SRC_ROOT = PROJECT_ROOT / "src"

LEFTHOOK_SCRIPT = '#!/bin/sh\n# lefthook\ncall_lefthook run "{hook}" "$@"\n'


def run_cli(
    *args: str,
    cwd: Path | None = None,
    env_extra: dict[str, str] | None = None,
    expected_returncode: int = 0,
) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env["PYTHONPATH"] = str(SRC_ROOT)
    if env_extra:
        env.update(env_extra)
    result = subprocess.run(
        [sys.executable, "-m", "agentdir", *args],
        cwd=cwd or PROJECT_ROOT,
        env=env,
        text=True,
        capture_output=True,
    )
    assert result.returncode == expected_returncode, (
        f"expected exit code {expected_returncode}, got {result.returncode}\n"
        f"stdout:\n{result.stdout}\n"
        f"stderr:\n{result.stderr}"
    )
    return result


def init_repo(path: Path) -> Path:
    path.mkdir()
    subprocess.run(["git", "init"], cwd=path, check=True, text=True, capture_output=True)
    subprocess.run(["git", "config", "user.email", "agentdir@example.test"], cwd=path, check=True)
    subprocess.run(["git", "config", "user.name", "AgentDir Test"], cwd=path, check=True)
    return path


def adopt(repo: Path, home: Path, *extra: str) -> dict[str, object]:
    result = run_cli(
        "adopt",
        "--install-skill",
        "none",
        "--gitignore",
        "none",
        "--no-hooks",
        *extra,
        "--json",
        cwd=repo,
        env_extra={"HOME": str(home)},
    )
    return json.loads(result.stdout)


def test_adopt_redirects_integrations_to_rulesync_source_rule(tmp_path: Path) -> None:
    repo = init_repo(tmp_path / "repo")
    home = tmp_path / "home"
    home.mkdir()
    (repo / ".rulesync" / "rules").mkdir(parents=True)

    payload = adopt(repo, home)
    rule = repo / ".rulesync" / "rules" / "agentdir.md"

    assert [generator["name"] for generator in payload["environment"]["rule_generators"]] == ["rulesync"]
    assert [item["name"] for item in payload["integrations"]] == ["rulesync"]
    assert any("rulesync" in warning for warning in payload["warnings"])
    skipped = {adjustment["name"] for adjustment in payload["adjustments"]}
    assert {"generic", "claude", "copilot", "cursor", "windsurf"} == skipped
    assert rule.is_file()
    rule_text = rule.read_text(encoding="utf-8")
    assert rule_text.startswith("---\nroot: false\n")
    assert 'targets: ["*"]' in rule_text
    assert "<!-- agentdir-managed-rulesync:start -->" in rule_text
    assert "agentdir work start" in rule_text
    assert not (repo / "CLAUDE.md").exists()
    assert not (repo / "AGENTS.md").exists()
    assert not (repo / ".cursor").exists()
    assert not (repo / ".windsurf").exists()
    assert not (repo / ".github").exists()


def test_adopt_project_files_mode_writes_tool_files_despite_rulesync(tmp_path: Path) -> None:
    repo = init_repo(tmp_path / "repo")
    home = tmp_path / "home"
    home.mkdir()
    (repo / ".rulesync" / "rules").mkdir(parents=True)

    payload = adopt(repo, home, "--install-integrations", "project-files")

    assert (repo / "CLAUDE.md").is_file()
    assert (repo / "AGENTS.md").is_file()
    assert not (repo / ".rulesync" / "rules" / "agentdir.md").exists()
    assert any("project-files" in warning for warning in payload["warnings"])


def test_adopt_skips_generated_marker_files(tmp_path: Path) -> None:
    repo = init_repo(tmp_path / "repo")
    home = tmp_path / "home"
    home.mkdir()
    claude = repo / "CLAUDE.md"
    generated = "<!-- AUTO-GENERATED by ruler. DO NOT EDIT. -->\n\n# Rules\n\nGenerated content.\n"
    claude.write_text(generated, encoding="utf-8")

    payload = adopt(repo, home)

    claude_entry = next(item for item in payload["integrations"] if item["name"] == "claude")
    assert claude_entry["skipped"] and "generated" in claude_entry["skipped"]
    assert claude.read_text(encoding="utf-8") == generated
    agents_text = (repo / "AGENTS.md").read_text(encoding="utf-8")
    assert "agentdir-managed-generic:start" in agents_text

    doctor = json.loads(
        run_cli("integrations", "doctor", "--json", cwd=repo, env_extra={"HOME": str(home)}).stdout
    )
    claude_check = next(check for check in doctor["checks"] if check["name"] == "claude")
    assert claude_check["state"] == "generated"
    assert doctor["ok"] is True


def test_unadopt_removes_rulesync_source_rule(tmp_path: Path) -> None:
    repo = init_repo(tmp_path / "repo")
    home = tmp_path / "home"
    home.mkdir()
    (repo / ".rulesync" / "rules").mkdir(parents=True)
    adopt(repo, home)
    rule = repo / ".rulesync" / "rules" / "agentdir.md"
    assert rule.is_file()

    run_cli("unadopt", "--apply", "--json", cwd=repo, env_extra={"HOME": str(home)})

    assert not rule.exists()
    assert (repo / ".agentdir").is_dir()


def test_hooks_manifest_written_and_doctor_flags_clobbered_hook(tmp_path: Path) -> None:
    repo = init_repo(tmp_path / "repo")
    run_cli("hooks", "install", "--hook", "pre-commit", cwd=repo)

    manifest = json.loads((repo / ".agentdir" / "hooks.json").read_text(encoding="utf-8"))
    assert manifest["hooks"] == ["pre-commit"]
    assert manifest["repo"] == str(repo.resolve())

    clean = json.loads(run_cli("doctor", "--json", cwd=repo).stdout)
    assert not any("pre-commit" in warning for warning in clean["warnings"])

    hook = repo / ".git" / "hooks" / "pre-commit"
    hook.write_text(LEFTHOOK_SCRIPT.format(hook="pre-commit"), encoding="utf-8")
    report = json.loads(run_cli("doctor", "--json", cwd=repo).stdout)

    assert report["ok"] is True
    assert any(
        "pre-commit" in warning and "overwritten by lefthook" in warning
        for warning in report["warnings"]
    )

    hook.unlink()
    report = json.loads(run_cli("doctor", "--json", cwd=repo).stdout)
    assert any("missing" in warning and "pre-commit" in warning for warning in report["warnings"])


def test_hooks_install_self_heals_after_hook_manager_reinstall(tmp_path: Path) -> None:
    repo = init_repo(tmp_path / "repo")
    hook = repo / ".git" / "hooks" / "pre-commit"
    hook.write_text(LEFTHOOK_SCRIPT.format(hook="pre-commit") + "# v1\n", encoding="utf-8")
    hook.chmod(0o755)

    run_cli("hooks", "install", "--hook", "pre-commit", cwd=repo)
    original = repo / ".git" / "hooks" / "pre-commit.agentdir-original"
    assert "# v1" in original.read_text(encoding="utf-8")

    # Simulate `lefthook install` clobbering the shim with a fresh script.
    hook.write_text(LEFTHOOK_SCRIPT.format(hook="pre-commit") + "# v2\n", encoding="utf-8")
    result = run_cli("hooks", "install", "--hook", "pre-commit", cwd=repo)

    assert "chains lefthook" in result.stdout
    assert "AgentDir managed hook" in hook.read_text(encoding="utf-8")
    assert "# v2" in original.read_text(encoding="utf-8")

    status = json.loads(run_cli("hooks", "status", "--hook", "pre-commit", "--json", cwd=repo).stdout)
    assert status[0]["managed"] is True


def test_hooks_install_still_refuses_when_backup_is_custom(tmp_path: Path) -> None:
    repo = init_repo(tmp_path / "repo")
    hook = repo / ".git" / "hooks" / "pre-commit"
    hook.write_text("#!/bin/sh\necho custom-hook\n", encoding="utf-8")
    hook.chmod(0o755)

    run_cli("hooks", "install", "--hook", "pre-commit", cwd=repo)
    hook.write_text(LEFTHOOK_SCRIPT.format(hook="pre-commit"), encoding="utf-8")

    refused = run_cli("hooks", "install", "--hook", "pre-commit", cwd=repo, expected_returncode=2)
    assert "Refusing to overwrite" in refused.stderr
    original = repo / ".git" / "hooks" / "pre-commit.agentdir-original"
    assert "custom-hook" in original.read_text(encoding="utf-8")


def test_doctor_warns_when_core_hookspath_bypasses_shims(tmp_path: Path) -> None:
    repo = init_repo(tmp_path / "repo")
    run_cli("hooks", "install", "--hook", "pre-commit", cwd=repo)

    subprocess.run(["git", "config", "core.hooksPath", ".githooks"], cwd=repo, check=True)
    report = json.loads(run_cli("doctor", "--json", cwd=repo).stdout)

    assert any("core.hooksPath" in warning and "bypasses" in warning for warning in report["warnings"])


def test_hooks_install_in_linked_worktree_targets_shared_hooks_dir(tmp_path: Path) -> None:
    repo = init_repo(tmp_path / "repo")
    (repo / "README.md").write_text("hello\n", encoding="utf-8")
    subprocess.run(["git", "add", "README.md"], cwd=repo, check=True)
    subprocess.run(
        ["git", "commit", "-m", "init"],
        cwd=repo,
        check=True,
        text=True,
        capture_output=True,
    )
    worktree = tmp_path / "wt"
    subprocess.run(
        ["git", "worktree", "add", str(worktree)],
        cwd=repo,
        check=True,
        text=True,
        capture_output=True,
    )

    run_cli("hooks", "install", "--hook", "pre-commit", cwd=worktree)

    shared_hook = repo / ".git" / "hooks" / "pre-commit"
    assert shared_hook.is_file()
    assert "AgentDir managed hook" in shared_hook.read_text(encoding="utf-8")
    assert not (repo / ".git" / "worktrees" / worktree.name / "hooks" / "pre-commit").exists()


def test_adopt_dry_run_reports_hook_managers(tmp_path: Path) -> None:
    repo = init_repo(tmp_path / "repo")
    home = tmp_path / "home"
    home.mkdir()
    (repo / "lefthook.yml").write_text("pre-commit:\n  jobs:\n    - run: echo lint\n", encoding="utf-8")
    (repo / ".husky").mkdir()
    (repo / ".pre-commit-config.yaml").write_text("repos: []\n", encoding="utf-8")
    (repo / "package.json").write_text(
        json.dumps({"devDependencies": {"lefthook": "^1.0.0"}}), encoding="utf-8"
    )

    plan = json.loads(
        run_cli(
            "adopt",
            "--dry-run",
            "--gitignore",
            "none",
            "--json",
            cwd=repo,
            env_extra={"HOME": str(home)},
        ).stdout
    )

    managers = {manager["name"] for manager in plan["environment"]["hook_managers"]}
    assert {"lefthook", "husky", "pre-commit"} <= managers
    lefthook = next(m for m in plan["environment"]["hook_managers"] if m["name"] == "lefthook")
    assert str(repo / "lefthook.yml") in lefthook["evidence"]
    assert str(repo / "package.json") in lefthook["evidence"]
    assert any("lefthook" in warning for warning in plan["warnings"])
    assert not (repo / ".agentdir").exists()
