"""Detect repo tooling that owns files AgentDir would otherwise manage.

Rule generators (rulesync) regenerate agent guidance files, wiping managed
blocks. Hook managers (lefthook, husky, pre-commit) reinstall Git hooks,
overwriting AgentDir hook shims. Adoption and doctor use these detectors to
place managed content where it survives and to flag when recording goes quiet.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from .git import git_output, git_root

RULE_GENERATOR_RULESYNC = "rulesync"
HOOK_MANAGER_LEFTHOOK = "lefthook"
HOOK_MANAGER_HUSKY = "husky"
HOOK_MANAGER_PRE_COMMIT = "pre-commit"
HOOK_MANAGER_CORE_HOOKSPATH = "core.hooksPath"

RULESYNC_DIR = ".rulesync"
RULESYNC_CONFIG_FILES = ("rulesync.jsonc", "rulesync.json")
LEFTHOOK_CONFIG_FILES = (
    "lefthook.yml",
    "lefthook.yaml",
    "lefthook.toml",
    "lefthook.json",
    ".lefthook.yml",
    ".lefthook.yaml",
)
PRE_COMMIT_CONFIG_FILES = (".pre-commit-config.yaml", ".pre-commit-config.yml")

GENERATED_FILE_MARKERS = (
    "do not edit",
    "@generated",
    "auto-generated",
    "autogenerated",
    "generated by",
)
GENERATED_SNIFF_LINES = 10

HOOK_OWNER_SIGNATURES: tuple[tuple[str, tuple[str, ...]], ...] = (
    (HOOK_MANAGER_LEFTHOOK, ("lefthook",)),
    (HOOK_MANAGER_HUSKY, ("husky",)),
    (HOOK_MANAGER_PRE_COMMIT, ("pre-commit.com",)),
)


@dataclass(frozen=True)
class RuleGenerator:
    name: str
    evidence: list[str] = field(default_factory=list)
    source_dir: str | None = None


@dataclass(frozen=True)
class HookManager:
    name: str
    evidence: list[str] = field(default_factory=list)
    hooks_path: str | None = None


def detect_rule_generators(cwd: str | Path | None = None) -> list[RuleGenerator]:
    project = git_root(cwd)
    if project is None:
        return []
    evidence: list[str] = []
    rulesync_dir = project / RULESYNC_DIR
    if rulesync_dir.is_dir():
        evidence.append(str(rulesync_dir))
    for name in RULESYNC_CONFIG_FILES:
        candidate = project / name
        if candidate.is_file():
            evidence.append(str(candidate))
    if not evidence:
        return []
    return [
        RuleGenerator(
            name=RULE_GENERATOR_RULESYNC,
            evidence=evidence,
            source_dir=str(rulesync_dir / "rules"),
        )
    ]


def detect_hook_managers(cwd: str | Path | None = None) -> list[HookManager]:
    project = git_root(cwd)
    if project is None:
        return []
    managers: list[HookManager] = []
    package_dependencies = _package_json_dependencies(project)

    lefthook_evidence = [
        str(project / name) for name in LEFTHOOK_CONFIG_FILES if (project / name).is_file()
    ]
    if HOOK_MANAGER_LEFTHOOK in package_dependencies:
        lefthook_evidence.append(str(project / "package.json"))
    if lefthook_evidence:
        managers.append(HookManager(name=HOOK_MANAGER_LEFTHOOK, evidence=lefthook_evidence))

    husky_evidence: list[str] = []
    if (project / ".husky").is_dir():
        husky_evidence.append(str(project / ".husky"))
    if HOOK_MANAGER_HUSKY in package_dependencies:
        husky_evidence.append(str(project / "package.json"))
    if husky_evidence:
        managers.append(HookManager(name=HOOK_MANAGER_HUSKY, evidence=husky_evidence))

    pre_commit_evidence = [
        str(project / name) for name in PRE_COMMIT_CONFIG_FILES if (project / name).is_file()
    ]
    if pre_commit_evidence:
        managers.append(HookManager(name=HOOK_MANAGER_PRE_COMMIT, evidence=pre_commit_evidence))

    hooks_path = git_output(["config", "--get", "core.hooksPath"], cwd or project)
    if hooks_path:
        managers.append(
            HookManager(
                name=HOOK_MANAGER_CORE_HOOKSPATH,
                evidence=[f"git config core.hooksPath={hooks_path}"],
                hooks_path=hooks_path,
            )
        )
    return managers


def detect_environment(cwd: str | Path | None = None) -> dict[str, Any]:
    return {
        "rule_generators": [asdict(generator) for generator in detect_rule_generators(cwd)],
        "hook_managers": [asdict(manager) for manager in detect_hook_managers(cwd)],
    }


def generated_file_marker(text: str) -> str | None:
    """Return the header line that marks ``text`` as generated, if any."""
    for line in text.splitlines()[:GENERATED_SNIFF_LINES]:
        lowered = line.lower()
        for marker in GENERATED_FILE_MARKERS:
            if marker in lowered:
                return line.strip()
    return None


def identify_hook_owner(text: str) -> str | None:
    """Identify which hook manager generated a non-AgentDir hook script."""
    lowered = text.lower()
    for owner, signatures in HOOK_OWNER_SIGNATURES:
        if any(signature in lowered for signature in signatures):
            return owner
    return None


def has_rule_generator(environment: dict[str, Any], name: str = RULE_GENERATOR_RULESYNC) -> bool:
    return any(
        generator.get("name") == name for generator in environment.get("rule_generators") or []
    )


def _package_json_dependencies(project: Path) -> set[str]:
    package_json = project / "package.json"
    if not package_json.is_file():
        return set()
    try:
        data = json.loads(package_json.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return set()
    if not isinstance(data, dict):
        return set()
    dependencies: set[str] = set()
    for key in ("dependencies", "devDependencies"):
        section = data.get(key)
        if isinstance(section, dict):
            dependencies.update(section.keys())
    return dependencies
